Repository googleapis/java-orgpolicy, pull requests merged in 2021-09, with the labels that each got.

#244 ci: removing linkage-monitor from the required checks
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full, api: orgpolicy

#251 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, api: orgpolicy

#236 chore: update gapic-generator-java version to 2.1.0
  google-cloud-orgpolicy/src/main/java/com/google/cloud/orgpolicy/v2/stub/OrgPolicyStubSettings.java
  synth.metadata
Labels: cla: yes, context: full, api: orgpolicy

#262 chore: make owlbot check required
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: orgpolicy

#257 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  renovate.json
Labels: automerge, cla: yes, api: orgpolicy

#266 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: orgpolicy

#267 chore: change branch master to main in github configurations
  README.md
Labels: automerge, cla: yes, api: orgpolicy
