Repository googleapis/java-orgpolicy, pull requests merged in 2021-07, with the labels that each got.

#213 chore: remove distributionManagement section
  pom.xml
Labels: api: orgpolicy, automerge, cla: yes

#214 chore: remove distributionManagement section
  google-cloud-orgpolicy-bom/pom.xml
Labels: api: orgpolicy, automerge, cla: yes

#215 chore: remove All rights reserved clause from java.header
  java.header
  synth.metadata
Labels: api: orgpolicy, automerge, cla: yes, context: full

#216 chore: add dependencyDashboardLabels to renovate.json
  renovate.json
  synth.metadata
Labels: api: orgpolicy, automerge, cla: yes, context: full

#221 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: organizationpolicy, automerge, cla: yes

#222 feat: configure initial sp version
  .github/workflows/ci.yaml
Labels: api: organizationpolicy, automerge, cla: yes
